# Stage 2 — Data Preprocessing

This stage focuses on cleaning and preparing the dataset for machine learning models.

The preprocessing steps include:
- handling missing values
- fixing data inconsistencies
- converting categorical variables into numerical format
- encoding features
- preparing the dataset for training and testing

In [ ]:
# =====================================
# Import Libraries
# =====================================
import pandas as pd
import numpy as np

df = pd.read_csv("../data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
# Check for missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [3]:

# Check for empty strings
(df == " ").sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [4]:
# TotalCharges should be numerical, but it is stored as text because of empty values.
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# Check for missing values again
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [5]:
# Check rows where TotalCharges became missing
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [6]:
# Replace missing TotalCharges with 0:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

# Check for missing values again
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
# Check for duplicates
df.duplicated().sum()

np.int64(0)

In [8]:
df = df.drop_duplicates()

# Check again
df.duplicated().sum()

np.int64(0)

In [9]:
# customerID is only an identifier. It does not help the model predict churn.
df = df.drop("customerID", axis=1)

# Check duplicate feature rows after removing customerID
print("Duplicate feature rows after removing customerID:", df.duplicated().sum())

Duplicate feature rows after removing customerID: 22

In [10]:
# Check unique values in categorical columns
categorical_cols = df.select_dtypes(include=["object", "string"]).columns

for col in categorical_cols:
    print(col)
    print(df[col].unique())
    print("-" * 40)

gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
----------------------------------------
Partner
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
----------------------------------------
Dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------
PhoneService
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------
MultipleLines
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
----------------------------------------
InternetService
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
----------------------------------------
OnlineSecurity
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------
OnlineBackup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
----------------------------------------
DeviceProtection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------
TechSupport
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------
StreamingTV
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------
StreamingMovies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
----------------------------------------
Contract
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
----------------------------------------
PaperlessBilling
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
----------------------------------------
PaymentMethod
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
----------------------------------------
Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
----------------------------------------

In [11]:
# Convert target variable Churn to binary
df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

# Check
df["Churn"].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [12]:
# Convert binary categorical variables to binary data system
binary_cols = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling"
]

df["gender"] = df["gender"].map({"Male": 1, "Female": 0})

for col in ["Partner", "Dependents", "PhoneService", "PaperlessBilling"]:
    df[col] = df[col].map({"Yes": 1, "No": 0})

# Check results
df[binary_cols].head()

   gender  Partner  Dependents  PhoneService  PaperlessBilling
0       0        1           0             0                 1
1       1        0           0             1                 0
2       1        0           0             1                 1
3       1        0           0             0                 0
4       0        0           0             1                 1

In [13]:
# Apply One-Hot Encoding to multi-category variables
multi_category_cols = [
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaymentMethod"
]

df = pd.get_dummies(df, columns=multi_category_cols, drop_first=True)

In [14]:
# Check the new shape
df.shape

(7043, 31)

In [15]:
# Check datatypes
df.dtypes

gender                                     int64
SeniorCitizen                              int64
Partner                                    int64
Dependents                                 int64
tenure                                     int64
PhoneService                               int64
PaperlessBilling                           int64
MonthlyCharges                           float64
TotalCharges                             float64
Churn                                      int64
MultipleLines_No phone service              bool
MultipleLines_Yes                           bool
InternetService_Fiber optic                 bool
InternetService_No                          bool
OnlineSecurity_No internet service          bool
OnlineSecurity_Yes                          bool
OnlineBackup_No internet service            bool
OnlineBackup_Yes                            bool
DeviceProtection_No internet service        bool
DeviceProtection_Yes                        bool
TechSupport_No internet service             bool
TechSupport_Yes                             bool
StreamingTV_No internet service             bool
StreamingTV_Yes                             bool
StreamingMovies_No internet service         bool
StreamingMovies_Yes                         bool
Contract_One year                           bool
Contract_Two year                           bool
PaymentMethod_Credit card (automatic)       bool
PaymentMethod_Electronic check              bool
PaymentMethod_Mailed check                  bool
dtype: object

In [16]:
# Convert only boolean columns to integers
bool_cols = df.select_dtypes(include=["bool"]).columns
df[bool_cols] = df[bool_cols].astype(int)

# Check datatypes
df.dtypes

gender                                     int64
SeniorCitizen                              int64
Partner                                    int64
Dependents                                 int64
tenure                                     int64
PhoneService                               int64
PaperlessBilling                           int64
MonthlyCharges                           float64
TotalCharges                             float64
Churn                                      int64
MultipleLines_No phone service             int64
MultipleLines_Yes                          int64
InternetService_Fiber optic                int64
InternetService_No                         int64
OnlineSecurity_No internet service         int64
OnlineSecurity_Yes                         int64
OnlineBackup_No internet service           int64
OnlineBackup_Yes                           int64
DeviceProtection_No internet service       int64
DeviceProtection_Yes                       int64
TechSupport_No internet service            int64
TechSupport_Yes                            int64
StreamingTV_No internet service            int64
StreamingTV_Yes                            int64
StreamingMovies_No internet service        int64
StreamingMovies_Yes                        int64
Contract_One year                          int64
Contract_Two year                          int64
PaymentMethod_Credit card (automatic)      int64
PaymentMethod_Electronic check             int64
PaymentMethod_Mailed check                 int64
dtype: object

In [17]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,0,...,0,0,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,0,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,1,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,1,0,0,0,0,1,0,0,0,0
4,0,0,0,0,2,1,1,70.70,151.65,1,...,0,0,0,0,0,0,0,0,1,0

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   int64
 1   SeniorCitizen                          7043 non-null   int64
 2   Partner                                7043 non-null   int64
 3   Dependents                             7043 non-null   int64
 4   tenure                                 7043 non-null   int64
 5   PhoneService                           7043 non-null   int64
 6   PaperlessBilling                       7043 non-null   int64
 7   MonthlyCharges                         7043 non-null   float64
 8   TotalCharges                           7043 non-null   float64
 9   Churn                                  7043 non-null   int64
 10  MultipleLines_No phone service         7043 non-null   int64
 11  MultipleLines_Yes                      7043 non-null   int64
 12  InternetService_Fiber optic            7043 non-null   int64
 13  InternetService_No                     7043 non-null   int64
 14  OnlineSecurity_No internet service     7043 non-null   int64
 15  OnlineSecurity_Yes                     7043 non-null   int64
 16  OnlineBackup_No internet service       7043 non-null   int64
 17  OnlineBackup_Yes                       7043 non-null   int64
 18  DeviceProtection_No internet service   7043 non-null   int64
 19  DeviceProtection_Yes                   7043 non-null   int64
 20  TechSupport_No internet service        7043 non-null   int64
 21  TechSupport_Yes                        7043 non-null   int64
 22  StreamingTV_No internet service        7043 non-null   int64
 23  StreamingTV_Yes                        7043 non-null   int64
 24  StreamingMovies_No internet service    7043 non-null   int64
 25  StreamingMovies_Yes                    7043 non-null   int64
 26  Contract_One year                      7043 non-null   int64
 27  Contract_Two year                      7043 non-null   int64
 28  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 29  PaymentMethod_Electronic check         7043 non-null   int64
 30  PaymentMethod_Mailed check             7043 non-null   int64
dtypes: float64(2), int64(29)
memory usage: 1.7 MB

In [19]:
print("Missing values:", df.isnull().sum().sum())
print("Shape:", df.shape)
print("Duplicate feature rows:", df.duplicated().sum())
# Important point: after dropping customerID, two different customers may look identical 
# because all their features are the same. So these are not necessarily “duplicate records” 
# in the original dataset — they may be different customers with the same profile.

Missing values: 0
Shape: (7043, 31)
Duplicate feature rows: 22

In [20]:
df.to_csv("../data/telco_churn_cleaned_encoded.csv", index=False)